name: CI
on:
  workflow_dispatch: ~
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"
    tags:
      - "*"
defaults:
  run:
    shell: bash
env:
  JULIA_NUM_THREADS: auto
  JULIA_PKG_USE_CLI_GIT: true
jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        julia-version:
          - "1.9"
          - "1.10"
          - "1.11"
          - "pre"
          - "1.11-nightly"
          - "1.12-nightly"
        include:
          - { experimental: false }
          - { experimental: true, julia-version: "1.11-nightly" }
          - { experimental: true, julia-version: "1.12-nightly" }
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: julia-actions/setup-julia@v2
        with:
          show-versioninfo: true
          version: ${{ matrix.julia-version }}
        env:
          JULIA_IS_EXPERIMENTAL: ${{ matrix.experimental }}
      - uses: julia-actions/julia-buildpkg@v1
        with:
          ignore-no-cache: true
          localregistry: https://github.com/0h7z/0hjl.git
      - uses: julia-actions/julia-runtest@v1
      - uses: heptazhou/julia-codecov@v1
        with:
          dirs: src:ext
      - uses: codecov/codecov-action@v4
        with:
          file: lcov.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: julia-actions/setup-julia@v2
        with:
          show-versioninfo: true
          version: "1"
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
